name: Deploy Admin to Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    name: Build and Deploy Admin to Staging Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build application
      run: npm run build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to staging server
      run: |
        # Create temporary directory for upload
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /tmp/staging-admin-dist"
        
        # Upload new build
        scp -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/tmp/staging-admin-dist/
        
        # Move files to staging location
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo rm -rf /var/www/staging-admin/*
          sudo cp -r /tmp/staging-admin-dist/* /var/www/staging-admin/
          sudo chown -R www-data:www-data /var/www/staging-admin
          sudo chmod -R 755 /var/www/staging-admin
          rm -rf /tmp/staging-admin-dist
        EOF

    - name: Verify staging deployment
      run: |
        sleep 10
        curl -f https://staging.cms.inseat.achievengine.com || exit 1
        echo "✅ Admin Staging deployment successful!"